language: python
python:
- '3.3'
- '3.4'
- '3.5'
install: pip install -r requirements.txt
script:
- cd json_compare/test
- py.test
deploy:
  provider: pypi
  user: darthghandi
  on:
    branch: master
  distributions: sdist bdist_wheel
  password:
    secure: Qmyk29gLatxOUqdVfS708dAM/TyMeD+/iSI8cZZNmEc0LfZAqD5IvrBZWkhOfYcNucDfmQBFiaos+5UoW4KhDl4lrS+mFBOaqZ7cpLO2gQt0x8cHVNemWlX+NHrIt5T+DmUufJMJyK0FFbony7N7AAFUzhTyQSyhMgOWmz/7+HoA536yuWGLVUiVSrdT1IGPTD1RGrcRvV105QqltN4zBM2q0/c9wlRjvIL8HhiuiHVSKxvx0XifrLkFmIKhZiH8zU0FciKPCfHvPYRfaqwHqjya6syr4/O6kRMABtZMEqJTjmv0sshAmm3o+1iwB1KEnwMUChNr0upJntLiYm5Qtg87IZqBr6gSDJiBD8C0pLu7PvLtH34mjNVxc6HfKX6U18Qo78EQ/IpyB9Q75X7Eu8fj0DW4vlqw5o7XT4fCMZ3+7zNlivKUVzSX49A4eaGiF4ltHd/ZcGyIfE4ftLT9Z2XRzl1CDzZtbmL1slZtF9LT0pj281GMBwpUyv73tnuJkRSRJZDtUZ/iNMHU9k7uQwHcG5SuWzWm26bBtTg57e7QDqEZXtJ7jUCUw+A3r/yGrszyKWT4y02FDvaf9v3KGgUZ0rZLWSK9KSl9bT40xwyKbzqTeMzOMcMPp16Roc/AcgJRdl7BQM8GxtSbFXqGhDxmk4z8jbkkpVAI35Go9BM=
